[database]
# Use local service names inside compose.custom.yml
mongodb = "mongodb://database:27017"
redis = "redis://redis:6379/"

[rabbit]
host = "rabbit"

[hosts]
app = "https://stoat-dev.zasperhub.com"
api = "https://stoat-dev.zasperhub.com"
events = "wss://stoat-dev.zasperhub.com/ws"
autumn = "http://autumn:14704"
january = "http://january:14705"

[api.smtp]
host = ""
username = ""
password = ""
from_address = "development@revolt.chat"
reply_to = "support@revolt.chat"
port = 1025
use_tls = false
use_starttls = false

[files.s3]
endpoint = "http://minio:9000"
region = "minio"
access_key_id = "minioautumn"
secret_access_key = "minioautumn"
default_bucket = "attachments"
path_style_buckets = true

